### PR TITLE
Update Sparql and translator test for statVarObs queries

### PR DESCRIPTION
**Pull request by shifucun**
Still keep StatPop in test schema mapping to cover test for entity joins.

---
This change is [Reviewable](https://reviewable.io/reviews/datacommonsorg/mixer/479)

### CODE REVIEW

**Review by pradh — COMMENTED** [review]
Nice!

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/mixer/479#-:-MVXKSFNCyreAG6lLQxa:b-83sjoh)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @shifucun)

___
*[internal/translator/translate_test.go, line 538 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/479#-MVXIki34jS89F3TXSKk:-MVXIki34jS89F3TXSKl:bc02wfu) ([raw file](https://github.com/datacommonsorg/mixer/blob/5fa1bd7de966494e95374e1675670ab6da7697e5/internal/translator/translate_test.go#L538)):*
> ```
> measuredProperty ?sv ?measuredProperty,
> ```

nit: I wonder why we need measuredProperty if we have variableMeasured?  Or should we skip variableMeasured?
___
*[internal/translator/translate_test.go, line 1090 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/479#-MVXJ8XT4yvhPucP-WYx:-MVXJ8XT4yvhPucP-WYy:b-vnss59) ([raw file](https://github.com/datacommonsorg/mixer/blob/5fa1bd7de966494e95374e1675670ab6da7697e5/internal/translator/translate_test.go#L1090)):*
> ```
> "FROM `dc_v3.Place` AS _dc_v3_Place_1 " +
> ```

Since a place can have multiple types, I think joining with Instance table might be the more accurate one.  For example, a County is also often AdministrativeArea2.
___
*[test/integration/query_test.go, line 33 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/479#-MVXJug0EuXbaIi8dyAV:-MVXJug0EuXbaIi8dyAW:bgfaz0u) ([raw file](https://github.com/datacommonsorg/mixer/blob/5fa1bd7de966494e95374e1675670ab6da7697e5/test/integration/query_test.go#L33)):*
> ```Go
> 
> const (
> 	PopObs Mode = iota
> ```

Did not know iota :)

Are SvObs and General automatically of type Mode too, or do we need to call that out?

**Review by shifucun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/mixer/479)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @pradh)

___
*[internal/translator/translate_test.go, line 538 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/479#-MVXIki34jS89F3TXSKk:-MW6518N9ImKX5ZNOGPi:b-7wzs1q) ([raw file](https://github.com/datacommonsorg/mixer/blob/5fa1bd7de966494e95374e1675670ab6da7697e5/internal/translator/translate_test.go#L538)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> measuredProperty ?sv ?measuredProperty,
> ```

nit: I wonder why we need measuredProperty if we have variableMeasured?  Or should we skip variableMeasured?
</blockquote></details>

here is to test the join of observation -> sv -> mprop here, need the variableMeasured  to link observation and mprop
___
*[internal/translator/translate_test.go, line 1090 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/479#-MVXJ8XT4yvhPucP-WYx:-MW65tb-7TsxZowuQLzv:b-nwxem1) ([raw file](https://github.com/datacommonsorg/mixer/blob/5fa1bd7de966494e95374e1675670ab6da7697e5/internal/translator/translate_test.go#L1090)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> "FROM `dc_v3.Place` AS _dc_v3_Place_1 " +
> ```

Since a place can have multiple types, I think joining with Instance table might be the more accurate one.  For example, a County is also often AdministrativeArea2.
</blockquote></details>

If a place has multiple types, what would be the type in "Place" and "Instance" table?
___
*[test/integration/query_test.go, line 33 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/479#-MVXJug0EuXbaIi8dyAV:-MW66Uc215x39G-YAwOK:b-j16vfi) ([raw file](https://github.com/datacommonsorg/mixer/blob/5fa1bd7de966494e95374e1675670ab6da7697e5/test/integration/query_test.go#L33)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

Did not know iota :)

Are SvObs and General automatically of type Mode too, or do we need to call that out?
</blockquote></details>

yeah.. Go uses this way for enum definition: https://yourbasic.org/golang/iota/

**Review by pradh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/mixer/479)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @pradh and @shifucun)

___
*[internal/translator/translate_test.go, line 538 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/479#-MVXIki34jS89F3TXSKk:-MW6TCXwCe2Mz2iIuVpC:b-qara0y) ([raw file](https://github.com/datacommonsorg/mixer/blob/5fa1bd7de966494e95374e1675670ab6da7697e5/internal/translator/translate_test.go#L538)):*
<details><summary><i>Previously, shifucun (Bo Xu) wrote…</i></summary><blockquote>

here is to test the join of observation -> sv -> mprop here, need the variableMeasured  to link observation and mprop
</blockquote></details>

ah, nevermind, misread it.
___
*[internal/translator/translate_test.go, line 1090 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/479#-MVXJ8XT4yvhPucP-WYx:-MW6UJd83rTgw5eHGxDl:b-bv0w3h) ([raw file](https://github.com/datacommonsorg/mixer/blob/5fa1bd7de966494e95374e1675670ab6da7697e5/internal/translator/translate_test.go#L1090)):*
<details><summary><i>Previously, shifucun (Bo Xu) wrote…</i></summary><blockquote>

If a place has multiple types, what would be the type in "Place" and "Instance" table?
</blockquote></details>

Instance table will have multiple types.

**Comment by shifucun** [comment]
Thanks. I plan to revisit the table joins and potentially involve Instance table for this case

**Pull request merged**
