### PR TITLE
Coordinate recon: support type filtering

### PR DESCRIPTION
**Pull request by pradh**
This is to improve the performance of coordinate-recon API.  TBD how much it improves in practice.

More context in b/321108211

### CODE REVIEW

**Review by shifucun — APPROVED** [review]
nice!

**Comment by pradh** [comment]
Thanks for the review!

**Comment by shifucun** [comment]
Maybe add an example in https://docs.datacommons.org/api/rest/v2/resolve Example 2

**Comment by pradh** [comment]
> Maybe add an example in https://docs.datacommons.org/api/rest/v2/resolve Example 2

SG, will send a PR.

**Pull request merged**
