### PR TITLE
Send notification email on golden data diff from a new base Bigtable

### PR DESCRIPTION
**Pull request by shifucun**
This change is [Reviewable](https://reviewable.io/reviews/datacommonsorg/mixer/451)

### CODE REVIEW

**Review by pradh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/mixer/451)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @shifucun)

___
*[script/golden_diff_notify.sh, line 22 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/451#-MRkTj3G4sAMF5gYcFOB:-MRkTj3G4sAMF5gYcFOC:b-cpmhr5) ([raw file](https://github.com/datacommonsorg/mixer/blob/caa15610a4795803392276335db9ea288d1e38eb/script/golden_diff_notify.sh#L22)):*
> ```Shell
> set -e
> 
> BASE_VERSION=$1
> ```

nit: BASE_BT_VERSION
___
*[script/golden_diff_notify.sh, line 38 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/451#-MRkUN5V0-qodHH4prIt:-MRkUN5V0-qodHH4prIu:b2hf4us) ([raw file](https://github.com/datacommonsorg/mixer/blob/caa15610a4795803392276335db9ea288d1e38eb/script/golden_diff_notify.sh#L38)):*
> ```
> git diff | /tmp/ansi2html.sh > /tmp/golden-diff.html
> ```
Very cool!

Any pointer to the html?
___
*[tools/send_diff_email/main.go, line 31 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/451#-MRkUwN69Nq_Ma8Y8OdK:-MRkUwN69Nq_Ma8Y8OdL:b-nf9bx6) ([raw file](https://github.com/datacommonsorg/mixer/blob/caa15610a4795803392276335db9ea288d1e38eb/tools/send_diff_email/main.go#L31)):*
> ```
> var (
> 	basebt = flag.String("base_bt", "", "Base Bigtable version.")
> )
> ```

For your consideration... with a minor tweak this can be a general tool, called send_email. Instead of hardcoding subject and file, pass it in:
  --subject
  --body_file
___
*[tools/send_diff_email/main.go, line 57 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/451#-MRkU_WD56JfR2UnuWl9:-MRkU_WD56JfR2UnuWlA:b-d6rhw0) ([raw file](https://github.com/datacommonsorg/mixer/blob/caa15610a4795803392276335db9ea288d1e38eb/tools/send_diff_email/main.go#L57)):*
> ```
> datacommons+release @google.com
> ```

Is there a space before '@' ?
___
*[tools/send_diff_email/main.go, line 69 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/451#-MRkVffp2tn8gQs_0CKX:-MRkVffp2tn8gQs_0CKY:bj18wou) ([raw file](https://github.com/datacommonsorg/mixer/blob/caa15610a4795803392276335db9ea288d1e38eb/tools/send_diff_email/main.go#L69)):*
> ```
> from
> ```

s/from/for/

**Review by shifucun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/mixer/451)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @pradh)

___
*[script/golden_diff_notify.sh, line 38 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/451#-MRkUN5V0-qodHH4prIt:-MRkaneE9SguTis_KM_7:b-a0ubf0) ([raw file](https://github.com/datacommonsorg/mixer/blob/caa15610a4795803392276335db9ea288d1e38eb/script/golden_diff_notify.sh#L38)):*
> ansi2html
Added reference
___
*[tools/send_diff_email/main.go, line 31 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/451#-MRkUwN69Nq_Ma8Y8OdK:-MRkdCM2-8x-IQuS9Spx:b-e8513l) ([raw file](https://github.com/datacommonsorg/mixer/blob/caa15610a4795803392276335db9ea288d1e38eb/tools/send_diff_email/main.go#L31)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> var (
> 	basebt = flag.String("base_bt", "", "Base Bigtable version.")
> )
> ```

For your consideration... with a minor tweak this can be a general tool, called send_email. Instead of hardcoding subject and file, pass it in:
  --subject
  --body_file

</blockquote></details>

good point!
___
*[tools/send_diff_email/main.go, line 57 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/451#-MRkU_WD56JfR2UnuWl9:-MRkct3p90M7rSFxKPj0:b8h2s3) ([raw file](https://github.com/datacommonsorg/mixer/blob/caa15610a4795803392276335db9ea288d1e38eb/tools/send_diff_email/main.go#L57)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> datacommons+release @google.com
> ```

Is there a space before '@' ?
</blockquote></details>

good eye
___
*[tools/send_diff_email/main.go, line 69 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/451#-MRkVffp2tn8gQs_0CKX:-MRkdBcv9syJugu_-XTa:b-896fix) ([raw file](https://github.com/datacommonsorg/mixer/blob/caa15610a4795803392276335db9ea288d1e38eb/tools/send_diff_email/main.go#L69)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> from
> ```

s/from/for/
</blockquote></details>

Done.

**Review by shifucun — COMMENTED** [review]
thanks for review!

**Review by pradh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/mixer/451)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @shifucun)

___
*[script/golden_diff_notify.sh, line 38 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/451#-MRkUN5V0-qodHH4prIt:-MRkfPvL7Sgj4ijoy2sJ:bigrnw) ([raw file](https://github.com/datacommonsorg/mixer/blob/caa15610a4795803392276335db9ea288d1e38eb/script/golden_diff_notify.sh#L38)):*
<details><summary><i>Previously, shifucun (Bo Xu) wrote…</i></summary><blockquote>

> ansi2html
Added reference
</blockquote></details>

I meant the generated diff HTML :) I'm okay waiting for it to show up for real...

**Comment by shifucun** [comment]
> > _[Reviewable](https://reviewable.io/reviews/datacommonsorg/mixer/451)_ status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @shifucun)
> 
> _[script/golden_diff_notify.sh, line 38 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/451#-MRkUN5V0-qodHH4prIt:-MRkfPvL7Sgj4ijoy2sJ:bigrnw) ([raw file](https://github.com/datacommonsorg/mixer/blob/caa15610a4795803392276335db9ea288d1e38eb/script/golden_diff_notify.sh#L38)):_
> 
> Previously, shifucun (Bo Xu) wrote…
> > > ansi2html
> > > Added reference
> 
> I meant the generated diff HTML :) I'm okay waiting for it to show up for real...

Manually triggered it. The text is quite plain though. The html does have color information but I was not able to get it showing in the email body. A future improvement.

**Pull request merged**
