### PR TITLE
Use DailyWeather instead of WeeklyWeather table

### PR DESCRIPTION
**Pull request by shifucun**
image

### CODE REVIEW

**Review by pradh — APPROVED** [review]
Thanks for the change!

**Comment by pradh** [comment]
Any way to keep both?

**Comment by pradh** [comment]
> Any way to keep both?

One has monthly data from 1950, and the other has daily data.

**Comment by shifucun** [comment]
> > Any way to keep both?
> 
> One has monthly data from 1950, and the other has daily data.

We can introduce "MonthlyWeatherObservation" and "DailyWeatherObservation" type to differentiate them? I tried to use the observationPeriod predicate but it does not work right away, it may need some more translation change.

**Comment by pradh** [comment]
> > > Any way to keep both?
> > 
> > 
> > One has monthly data from 1950, and the other has daily data.
> 
> We can introduce "MonthlyWeatherObservation" and "DailyWeatherObservation" type to differentiate them? I tried to use the observationPeriod predicate but it does not work right away, it may need some more translation change.

Sure, since this is all only in the Browser, I think that type change would not be visible anywhere and we can improve on this later. Thanks!

This is so that we can demo that we have long historic data + predictions.

**Pull request merged**
