### PR TITLE
Test for rankings 

### PR DESCRIPTION
**Pull request by beets**
Checks if all the stat vars we use in charts have rankings at a few levels - still very coarse (doesn't test scoped rankings) but at least shows us some coverage.

Ideally should use the chart config directly instead of this munged list of stat vars.

### CODE REVIEW

**Review by shifucun — COMMENTED** [review]
random thought If the code can request to https://raw.githubusercontent.com/datacommonsorg/website/master/server/chart_config.json and take out the stat vars

**Comment by beets** [comment]
that's a good idea!

**Comment by beets** [comment]
Reads the config from website repo now. Lots still missing, but I think the data on staging doesn't have the fix from the weekend.

**Comment by tjann** [comment]
Yeah this push does not have the similar places fix. It should have ranking fix, though.

**Review by tjann — APPROVED** [review]

**Review by beets — COMMENTED** [review]
Updated this to write out missing rankings to a modified chart config golden file. Ptal, hope this helps us to debug ranking issues.

**Review by tjann — APPROVED** [review]

**Pull request merged**
