### PR TITLE
Update stat related APIs to use cache keyed by statvar dcid

### PR DESCRIPTION
**Pull request by shifucun**
This change is [Reviewable](https://reviewable.io/reviews/datacommonsorg/mixer/478)

### CODE REVIEW

**Review by pradh — CHANGES_REQUESTED** [review]
Nice!  So there are still no diffs?

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/mixer/478#-:-MVNlBnG3Xq0gLipxng3:bt3o0iz)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @shifucun)

___
*[internal/server/key.go, line 127 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/478#-MVNk8Iu1J4FbcH5epzZ:-MVNk8Iu1J4FbcH5epz_:b8jfzxm) ([raw file](https://github.com/datacommonsorg/mixer/blob/1c32738dcc3e4a92d9d2d66a246c46487ce83bac/internal/server/key.go#L127)):*
> ```Go
> }
> 
> func buildStatCollectionKeyNew(parentPlace, childType, date string, statVars []string) (
> ```

nit: use SVObs instead of New ?
___
*[test/integration/get_stat_series_test.go, line 113 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/478#-MVNkoEO62_JS5eA0tiS:-MVNkoEO62_JS5eA0tiT:b25gwi0) ([raw file](https://github.com/datacommonsorg/mixer/blob/1c32738dcc3e4a92d9d2d66a246c46487ce83bac/test/integration/get_stat_series_test.go#L113)):*
> ```
> index == 0
> ```

So we are updating the golden from popobs mode?  Add comment or better use a bool like:

isPopObsMode := (index == 0)
___
*[test/integration/get_stats_test.go, line 114 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/478#-MVNl5H38RwF4CrrSDhN:-MVNl5H38RwF4CrrSDhO:bh6jqe1) ([raw file](https://github.com/datacommonsorg/mixer/blob/9615ddeb27b7f18315e6bc58e33212a81503bcc4/test/integration/get_stats_test.go#L114)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
> 		{
> 			"BadStatsVar",
> 			[]string{"geoId/06"},
> 			"",
> 			"",
> 			false,
> 			true,
> 		},
> ```
</details>


Out of curiosity, what happens in this case in the new mode?

**Review by shifucun — COMMENTED** [review]
Right, no diffs

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/mixer/478#-:-MVNs-Hy97j2utz-sGfQ:b-msboli)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @pradh)

___
*[internal/server/key.go, line 127 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/478#-MVNk8Iu1J4FbcH5epzZ:-MVNrkdUCstYD6mQPef-:bb6un1j) ([raw file](https://github.com/datacommonsorg/mixer/blob/1c32738dcc3e4a92d9d2d66a246c46487ce83bac/internal/server/key.go#L127)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

nit: use SVObs instead of New ?
</blockquote></details>

Done
___
*[test/integration/get_stat_series_test.go, line 113 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/478#-MVNkoEO62_JS5eA0tiS:-MVNrnMW9J1c-UZarjfS:b-896fix) ([raw file](https://github.com/datacommonsorg/mixer/blob/1c32738dcc3e4a92d9d2d66a246c46487ce83bac/test/integration/get_stat_series_test.go#L113)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> index == 0
> ```

So we are updating the golden from popobs mode?  Add comment or better use a bool like:

isPopObsMode := (index == 0)
</blockquote></details>

Done.
___
*[test/integration/get_stats_test.go, line 114 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/478#-MVNl5H38RwF4CrrSDhN:-MVNroEU7dxi6eThuaQJ:bpfvgqc) ([raw file](https://github.com/datacommonsorg/mixer/blob/9615ddeb27b7f18315e6bc58e33212a81503bcc4/test/integration/get_stats_test.go#L114)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> 		{
> 			"BadStatsVar",
> 			[]string{"geoId/06"},
> 			"",
> 			"",
> 			false,
> 			true,
> 		},
> ```

Out of curiosity, what happens in this case in the new mode?
</blockquote></details>

It will return empty result, as there is no way to know to know if the input is valid statvar anymore..

**Review by pradh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/mixer/478)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @pradh and @shifucun)

___
*[test/integration/get_stats_test.go, line 114 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/478#-MVNl5H38RwF4CrrSDhN:-MVNz_2t4eEFMZHwjwmf:b-uj4fa9) ([raw file](https://github.com/datacommonsorg/mixer/blob/9615ddeb27b7f18315e6bc58e33212a81503bcc4/test/integration/get_stats_test.go#L114)):*
<details><summary><i>Previously, shifucun (Bo Xu) wrote…</i></summary><blockquote>

It will return empty result, as there is no way to know to know if the input is valid statvar anymore..
</blockquote></details>

In theory, we could look up the stat-var-id in triples cache to know. But probably not worth it...

**Comment by shifucun** [comment]
> > _[Reviewable](https://reviewable.io/reviews/datacommonsorg/mixer/478)_ status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @pradh and @shifucun)
> 
> _[test/integration/get_stats_test.go, line 114 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/478#-MVNl5H38RwF4CrrSDhN:-MVNz_2t4eEFMZHwjwmf:b-uj4fa9) ([raw file](https://github.com/datacommonsorg/mixer/blob/9615ddeb27b7f18315e6bc58e33212a81503bcc4/test/integration/get_stats_test.go#L114)):_
> 
> Previously, shifucun (Bo Xu) wrote…
> In theory, we could look up the stat-var-id in triples cache to know. But probably not worth it...

sg..

**Pull request merged**
