### PR TITLE
Revive deployment process with Kustomize and Skaffold

### PR DESCRIPTION
**Pull request by shifucun**
Current mixer deployment uses bare shell script to replace template yaml files. This is very error prone and no good validation. There are two popular tools to do the yaml templating and composition: Helm and Kustomize. Here we choose to use "[Kustomize](https://kubectl.docs.kubernetes.io/guides/introduction/kustomize/)" which is built into "kubectl". For staging/prod deploy, can use same Kustomize command on the corresponding yaml template.

The PR also setup the "[Skaffold](https://skaffold.dev/docs/quickstart/)" tool to do local Kubernets development on Minikube. It can work well with Kustomize and do code edit-refresh.

With this PR, the whole mixer development process is streamlined. 

Note: will delete /deployment folder when the continuous deployment is switched to use the process from this PR.

---
This change is [Reviewable](https://reviewable.io/reviews/datacommonsorg/mixer/422)

### CODE REVIEW

**Review by pradh — APPROVED** [review]
Thanks for the description. Can we add some of this to README?  Also, link to canonical documentation of technologies like Skaffold and Kustomize.

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/mixer/422#-:-MPpu5ZV1XCAxtETZCE0:b-v8kv30)* status: 0 of 26 files reviewed, 13 unresolved discussions (waiting on @beets, @pradh, and @shifucun)

___
*[README.md, line 3 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPptsmdCC0-dgOm6ROC:-MPptsme8ch-3zAzwPTN:bge0gi4) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/README.md#L3)):*
> ```
> can be
> ```
gets ?
___
*[skaffold.yaml, line 14 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpuKfo3ENo0AanlF3s:-MPpuKfo3ENo0AanlF3t:blqa2iu) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/skaffold.yaml#L14)):*
> ```YAML
> # See the License for the specific language governing permissions and
> # limitations under the License.
> ```

Header comment on what this is (for someone who does not know skaffold)?
___
*[deploy/README.md, line 3 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpuS5c0PgKqSIHoAG0:-MPpuS5c0PgKqSIHoAG1:b-3l01yd) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/deploy/README.md#L3)):*
> ```Markdown
> # Deployment Configuration
> 
> Mixer is deployed to Kubernetes cluster either locally on Minikube or in Google Kubernetes Engine.
> ```

Link to canonical minikube page/doc?
___
*[deploy/README.md, line 7 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpv73L28MyF0ki0TTf:-MPpv73L28MyF0ki0TTg:bxhdeuv) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/deploy/README.md#L7)):*
> ```Markdown
> ## Folder structure
> 
> * `db`: BigQuery and Bigtable version config
> ```

s/db/storage/ maybe more appropriate... but its ok
___
*[deploy/README.md, line 18 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpuk89Bvj0swhXlmc4:-MPpuk8A5BeXxOe_ylzc:billhdm) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/deploy/README.md#L18)):*
> ```
> # kubectl config use-context <CONTEXT_NAME>
> ```
Is this relevant?
___
*[deploy/README.md, line 20 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpwj2p4ow6Np_QMH_B:-MPpwj2p4ow6Np_QMH_C:b-e8k6ur) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/deploy/README.md#L20)):*
> ```
> kustomize build overlays/staging > staging.yaml
> kubectl apply -f staging.yaml
> ```
Can you list the overlays available here and what they are for (e.g., not sure about dev)? Don't see it in other README..
___
*[deploy/base/deployment.yaml, line 14 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpuucB6asPj8pMrmo8:-MPpuucB6asPj8pMrmo9:b8dils1) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/deploy/base/deployment.yaml#L14)):*
> ```YAML
> # See the License for the specific language governing permissions and
> # limitations under the License.
> ```

I don't see a README.md describing these in deploy/base, so lets add a comment for all the yamls?
___
*[deploy/overlays/dev/kustomization.yaml, line 14 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpvJlo2hk_pdIocsH6:-MPpvJlo2hk_pdIocsH7:b8lxk5o) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/deploy/overlays/dev/kustomization.yaml#L14)):*
> ```YAML
> # See the License for the specific language governing permissions and
> # limitations under the License.
> ```

Describe these?
___
*[deploy/overlays/staging/kustomization.yaml, line 1 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpvPwX9rmh0670fyUS:-MPpvPwX9rmh0670fyUT:bgj98op) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/deploy/overlays/staging/kustomization.yaml#L1)):*
> ```YAML
> # Copyright 2019 Google LLC
> ```

Is overlaps/production/kustomization.yaml meant to be empty?

Also, why not "prod"?
___
*[docs/developer_guide.md, line 7 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpvbPO3wCzzVCKKRq2:-MPpvbPO3wCzzVCKKRq3:b-l5wpor) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/docs/developer_guide.md#L7)):*
> ```
> tools
> ```

wow, so many!
___
*[docs/developer_guide.md, line 38 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpvmYE5Lm1oAaGgBE4:-MPpvmYE5Lm1oAaGgBE5:b8c9te6) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/docs/developer_guide.md#L38)):*
> ```Markdown
> minikube addons enable gcp-auth
> eval $(minikube docker-env)
> skallfold dev --port-foward
> ```

is skallfold the right command?
___
*[docs/developer_guide.md, line 65 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpwG6u-HaVOlvCJc-C:-MPpwG6u-HaVOlvCJc-D:bzebuun) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/docs/developer_guide.md#L65)):*
> ```
> ## Develop mixer locally as a Go server
> **NOTE** This can only develop and test the gRPC server but not the transcoding of [ESP](https://cloud.google.com/endpoints/docs/grpc/running-esp-localdev).
> ```
I assume this us a second approach to using Docker and Minikube?  why would we use one vs. other?

What does it mean it can "test gRPC server but not the transcoding of ESP" ... could you say that in terms of the user/API experience?
___
*[docs/developer_guide.md, line 104 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpw_JTBsTumqhg_q0u:-MPpw_JTBsTumqhg_q0v:brzfio3) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/docs/developer_guide.md#L104)):*
> ```
> ### Run Tests (Go)
> ```bash
> ./script/run_test.sh
> ```
> ### Update e2e test golden files (Go)
> ```bash
> ./script/update_golden_staging.sh
> ```
> ```
Does this duplicate stuff above?

**Review by shifucun — COMMENTED** [review]
> Current mixer deployment uses bare shell script to replace template yaml files. This is very error prone and no good validation. There are two popular tools to do the yaml templating and composition: Helm and Kustomize. Here we choose to use "Kustomize" which is built into "kubectl". For staging/prod deploy, can use same Kustomize command on the corresponding yaml template.
> The PR also setup the "Skaffold" tool to do local Kubernets development on Minikube. It can work well with Kustomize and do code edit-refresh.
> With this PR, the whole mixer development process is streamlined.

Added discussion of kustomize and skaffold to README as well

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/mixer/422#-:-MPpzZkO4L96HmhWRzFr:bdo96v6)* status: 0 of 26 files reviewed, 13 unresolved discussions (waiting on @beets, @pradh, and @shifucun)

___
*[skaffold.yaml, line 14 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpuKfo3ENo0AanlF3s:-MPq-_yj7xYFrGQy_QD6:bb6un1j) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/skaffold.yaml#L14)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

Header comment on what this is (for someone who does not know skaffold)?
</blockquote></details>

Done
___
*[deploy/README.md, line 3 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpuS5c0PgKqSIHoAG0:-MPq-rlL6Bv2gIbU0gR8:bb6un1j) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/deploy/README.md#L3)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

Link to canonical minikube page/doc?
</blockquote></details>

Done
___
*[deploy/README.md, line 7 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpv73L28MyF0ki0TTf:-MPq08z7DsXsB05fzuPR:b-896fix) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/deploy/README.md#L7)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

s/db/storage/ maybe more appropriate... but its ok
</blockquote></details>

Done.
___
*[deploy/README.md, line 18 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpuk89Bvj0swhXlmc4:-MPq0B7lEgHZVnKaWupc:bl448v8) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/deploy/README.md#L18)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> # kubectl config use-context <CONTEXT_NAME>
> ```
Is this relevant?
</blockquote></details>

Yes, this prompts user to choose the right GKE cluster. Added as a comment too
___
*[deploy/base/deployment.yaml, line 14 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpuucB6asPj8pMrmo8:-MPq4Pci6WzVITeq0qqP:b-896fix) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/deploy/base/deployment.yaml#L14)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

I don't see a README.md describing these in deploy/base, so lets add a comment for all the yamls?
</blockquote></details>

Done.
___
*[deploy/overlays/dev/kustomization.yaml, line 14 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpvJlo2hk_pdIocsH6:-MPq4QV84ITyA0z_eFpt:b-896fix) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/deploy/overlays/dev/kustomization.yaml#L14)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

Describe these?
</blockquote></details>

Done.
___
*[deploy/overlays/staging/kustomization.yaml, line 1 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpvPwX9rmh0670fyUS:-MPq4Vlb75riw_ruTa7J:b-qsleyu) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/deploy/overlays/staging/kustomization.yaml#L1)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

Is overlaps/production/kustomization.yaml meant to be empty?

Also, why not "prod"?
</blockquote></details>

Changed to prod. Yeah, it's not configured yet. I plan to make everything on staging working and update prod
___
*[docs/developer_guide.md, line 7 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpvbPO3wCzzVCKKRq2:-MPq4kju7ilUoCS-Mq7k:bfgp7x1) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/docs/developer_guide.md#L7)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> tools
> ```

wow, so many!
</blockquote></details>

Strictly speaking only part of them are needed... like if using docker, then Golang and protoc are not necessary... But just to list all of them so there is no surprise
___
*[docs/developer_guide.md, line 38 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpvmYE5Lm1oAaGgBE4:-MPq55qNEpGx86rquCsj:bd30ifx) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/docs/developer_guide.md#L38)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

is skallfold the right command?
</blockquote></details>

good catch
___
*[docs/developer_guide.md, line 65 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpwG6u-HaVOlvCJc-C:-MPq5dnw7meIHXkEfOjW:bx7webl) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/docs/developer_guide.md#L65)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> ## Develop mixer locally as a Go server
> **NOTE** This can only develop and test the gRPC server but not the transcoding of [ESP](https://cloud.google.com/endpoints/docs/grpc/running-esp-localdev).
> ```
I assume this us a second approach to using Docker and Minikube?  why would we use one vs. other?

What does it mean it can "test gRPC server but not the transcoding of ESP" ... could you say that in terms of the user/API experience?
</blockquote></details>

Updated. This meant to say only test gRPC server but not the REST api.
___
*[docs/developer_guide.md, line 104 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpw_JTBsTumqhg_q0u:-MPq5pHrEykD_SeBVQfZ:bz4r0qn) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/docs/developer_guide.md#L104)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> ### Run Tests (Go)
> ```bash
> ./script/run_test.sh
> ```
> ### Update e2e test golden files (Go)
> ```bash
> ./script/update_golden_staging.sh
> ```
> ```
Does this duplicate stuff above?
</blockquote></details>

This is for the Golang (non-Docker) mode. I guess the two modes here are not quite obvious here..?

**Review by shifucun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/mixer/422)* status: 0 of 26 files reviewed, 13 unresolved discussions (waiting on @beets and @pradh)

___
*[README.md, line 3 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPptsmdCC0-dgOm6ROC:-MPq6D0U9Q4_tMDVHgIK:b-896fix) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/README.md#L3)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> can be
> ```
gets ?
</blockquote></details>

Done.
___
*[deploy/README.md, line 20 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpwj2p4ow6Np_QMH_B:-MPq6EaM3vs38suAnVce:b-896fix) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/deploy/README.md#L20)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

> ```
> kustomize build overlays/staging > staging.yaml
> kubectl apply -f staging.yaml
> ```
Can you list the overlays available here and what they are for (e.g., not sure about dev)? Don't see it in other README..
</blockquote></details>

Done.

**Review by pradh — APPROVED** [review]
Thanks for the comments!

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/mixer/422#-:-MPq9rJY1TXKO6Hdxf0h:b-a09w3v)* status: 0 of 26 files reviewed, 15 unresolved discussions (waiting on @beets, @pradh, and @shifucun)

___
*[deploy/README.md, line 7 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpv73L28MyF0ki0TTf:-MPq8W-P8opdJvSQiC4i:b-we6nx1) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/deploy/README.md#L7)):*
<details><summary><i>Previously, shifucun (Bo Xu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thanks. s/db/storage/ in this README ?
___
*[deploy/overlays/dev/kustomization.yaml, line 16 at r3](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPq8qLm1bIozSDV3YvH:-MPq8qLm1bIozSDV3YvI:bxr6jos) ([raw file](https://github.com/datacommonsorg/mixer/blob/25094029f577d101db5a981938c8555b0b3ba062/deploy/overlays/dev/kustomization.yaml#L16)):*
> ```YAML
> 
> # Kustomization for dev mixer in local Minikube environment.
> # - Addes "dev" suffix to all the resources
> ```

nit: Adds
___
*[deploy/overlays/staging/kustomization.yaml, line 1 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpvPwX9rmh0670fyUS:-MPq90JoANFle4ppoPD_:b-dxcbts) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/deploy/overlays/staging/kustomization.yaml#L1)):*
<details><summary><i>Previously, shifucun (Bo Xu) wrote…</i></summary><blockquote>

Changed to prod. Yeah, it's not configured yet. I plan to make everything on staging working and update prod
</blockquote></details>

Makes sense.
___
*[deploy/overlays/staging/kustomization.yaml, line 15 at r3](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPq9D3W-19-3gArFAwU:-MPq9D3W-19-3gArFAwV:b-1etyc6) ([raw file](https://github.com/datacommonsorg/mixer/blob/25094029f577d101db5a981938c8555b0b3ba062/deploy/overlays/staging/kustomization.yaml#L15)):*
> ```YAML
> # limitations under the License.
> 
> # Kustomization for dev mixer in local Minikube environment.
> ```

staging mixer in real environment ?
___
*[docs/developer_guide.md, line 65 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpwG6u-HaVOlvCJc-C:-MPq9_wy31UmnrxA3rGU:b-yy56ve) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/docs/developer_guide.md#L65)):*
<details><summary><i>Previously, shifucun (Bo Xu) wrote…</i></summary><blockquote>

Updated. This meant to say only test gRPC server but not the REST api.
</blockquote></details>

Who uses the gRPC server?
___
*[docs/developer_guide.md, line 104 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpw_JTBsTumqhg_q0u:-MPq9exNBSXJkECw_4uw:b-eancyl) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/docs/developer_guide.md#L104)):*
<details><summary><i>Previously, shifucun (Bo Xu) wrote…</i></summary><blockquote>

This is for the Golang (non-Docker) mode. I guess the two modes here are not quite obvious here..?
</blockquote></details>

I see. We could have the common testing and golden file updates in a separate section? But ok for now.

**Review by shifucun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/mixer/422)* status: 0 of 26 files reviewed, 14 unresolved discussions (waiting on @beets and @pradh)

___
*[deploy/README.md, line 7 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpv73L28MyF0ki0TTf:-MPqAkYMBxkYMz2rmue5:bb6un1j) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/deploy/README.md#L7)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

thanks. s/db/storage/ in this README ?
</blockquote></details>

Done
___
*[deploy/overlays/dev/kustomization.yaml, line 16 at r3](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPq8qLm1bIozSDV3YvH:-MPqApY50IuFxi4u15u7:bb6un1j) ([raw file](https://github.com/datacommonsorg/mixer/blob/25094029f577d101db5a981938c8555b0b3ba062/deploy/overlays/dev/kustomization.yaml#L16)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

nit: Adds
</blockquote></details>

Done
___
*[deploy/overlays/staging/kustomization.yaml, line 1 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpvPwX9rmh0670fyUS:-MPqB13t0mbwty9fcxqO:b-896fix) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/deploy/overlays/staging/kustomization.yaml#L1)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

Makes sense.
</blockquote></details>

Done.
___
*[deploy/overlays/staging/kustomization.yaml, line 15 at r3](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPq9D3W-19-3gArFAwU:-MPqAxmGDDVGccQWedOz:bjasqlz) ([raw file](https://github.com/datacommonsorg/mixer/blob/25094029f577d101db5a981938c8555b0b3ba062/deploy/overlays/staging/kustomization.yaml#L15)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

staging mixer in real environment ?
</blockquote></details>

Yes, the actual staging mixer
___
*[docs/developer_guide.md, line 65 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpwG6u-HaVOlvCJc-C:-MPqAHsx9F-ebo7tj0pn:biyf9b0) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/docs/developer_guide.md#L65)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

Who uses the gRPC server?
</blockquote></details>

that's what we have now.. and it's not quite useful. Eventually when everyone is familiar with the docker process, we can deprecate all the non-docker mode. 
___
*[docs/developer_guide.md, line 104 at r1](https://reviewable.io/reviews/datacommonsorg/mixer/422#-MPpw_JTBsTumqhg_q0u:-MPqAaHk2hJkWkIlPWxx:b32wwp) ([raw file](https://github.com/datacommonsorg/mixer/blob/7c539b2698952e16795c6f54b2e370d7004979d6/docs/developer_guide.md#L104)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

I see. We could have the common testing and golden file updates in a separate section? But ok for now.
</blockquote></details>

sg

**Pull request merged**
